/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv --include-runtime=false` (hash: 78af17028a50ab918aa56e4f3fd2eed4)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env {
		NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
		AUDIO_BUCKET: R2Bucket;
		DB: D1Database;
		IMAGES: ImagesBinding;
		ASSETS: Fetcher;
		NEXTJS_ENV: string;
		WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXTJS_ENV">> {}
}
